# Generated by Django 4.0 on 2021-12-19 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='BoxElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('w', 'Wiki'), ('s', 'Submission')], max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elements', to='learning.box')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_boxes', to='course.submission')),
                ('wiki', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_boxes', to='course.wiki')),
            ],
        ),
        migrations.CreateModel(
            name='ShortTermUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('w', 'Wiki'), ('s', 'Submission')], max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='short_term_units', to='course.course')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='short_term_units', to='course.submission')),
                ('wiki', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='short_term_units', to='course.wiki')),
            ],
        ),
        migrations.CreateModel(
            name='ShortTermUnitActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('correct_answer', models.BooleanField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='learning.shorttermunit')),
            ],
        ),
        migrations.CreateModel(
            name='BoxElementActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('correct_answer', models.BooleanField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='learning.boxelement')),
            ],
        ),
    ]
