# Generated by Django 4.0 on 2021-12-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='transfer',
            field=models.ManyToManyField(blank=True, related_name='course_references', to='course.Course'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='all_wiki_references',
            field=models.ManyToManyField(blank=True, related_name='all_submissions', to='course.Wiki'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='direct_wiki_references',
            field=models.ManyToManyField(blank=True, related_name='submissions', to='course.Wiki'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='calculated_references',
            field=models.ManyToManyField(blank=True, related_name='calculated_wiki_references', to='course.Wiki'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='transfer',
            field=models.ManyToManyField(blank=True, related_name='wiki_references', to='course.Wiki'),
        ),
    ]
