# Generated by Django 4.0 on 2021-12-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_number_alter_course_transfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki',
            name='synonyms',
            field=models.TextField(blank=True),
        ),
    ]
